version : '3'
services :
  app-iudigital :
    build :
      context: .
    ports :
      - "8084:8084"
    environment :
      DATABASE_URL : jdbc:mysql://localhost:3306/prueba
      DATABASE_USERNAME : root
      DATABASE_PASSWORD : 123456
    networks :
      - iudigital
    depends_on :
      - basedatos

  basedatos :
    image : mysql:latest
    environment :
      MYSQL_ROOT_PASSWORD : 123456
      MYSQL_DATABASE : prueba
      MYSQL_USER : root
      MYSQL_PASSWORD : prueba
    ports :
      - "3306:3306"
    volumes :
      - db_data:/var/lib/mysql
    networks :
      - iudigital

networks :
  iudigital :

volumes :
  db_data :